Home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', homepage_view, name='home'),
]

ProjectC8/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('', include('Register.urls')),
    path('', include('Donation.urls')),
    path('', include('Program.urls')),
    path('', include('About.urls')),
    path('', include('login.urls')),
    path('', include(('login.urls', 'login'), namespace='login')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

login/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path(r'login/', login_view, name='login'),
    path(r'logout/', logout_view, name='logout'),
]

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import render
from django.contrib.auth import logout as logout_user

def login_view(request):
    return render(request, "Login.html")

def logout_view(request):
    logout_user(request)
    return render(request, "Login.html")

login/templates/Login.html
{% extends 'Base/Base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
        <title>SinarPerak - Login</title>
    {% endblock %}
    {% block scripts %}
        {{ block.super }}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    {% endblock %}
</head>

{% block content %}
    {% if user.is_authenticated %}
        <body style="background-color: ghostwhite;">
            <div class="container">
                <h1 class="display-3" style="text-align: center; font-family: Quicksand; color: black">Hello, {{ user.username }}!</h1>
                <div class="row justify-content-center my-auto">
                    <a href="{% url 'login:logout' %}"><button class="btn" style="font-size: 25px">
                            <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
                            Logout</button></a>
                </div>
            </div>
        </body>
    {% else %}
        <body style="background-color: #222222;">
        <div class="container">
                <h1 class="display-3" style="text-align: center; font-family: Quicksand; color: whitesmoke">Hello..., sorry, who are you?</h1>
                <div class="row justify-content-center my-auto">
                    <a href="{% url 'social:begin' 'google-oauth2' %}"><button class="btn white" style="font-size: 25px">
                        <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
                        Login with Google</button></a>
                </div>
            </div>
        </body>
    {% endif %}

{% endblock %}
</html>