Home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', homepage_view, name='home'),
]

Program/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('program-1/', program, name='program-1'),
    path('program-2/', program, name='program-2'),
    path('program-3/', program, name='program-3'),
    path('program-4/', program, name='program-4'),
    path('program-5/', program, name='program-5'),
    path('program-6/', program, name='program-6'),
    path('program-7/', program, name='program-7'),
    path('program-8/', program, name='program-8'),
    path('program-9/', program, name='program-9'),
    path('program-10/', program, name='program-10'),
]

ProjectC8/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('', include('Register.urls')),
    path('', include('Donation.urls')),
    path('', include('Program.urls')),
    path('', include('About.urls')),
    path('', include('login.urls')),
    path('', include(('login.urls', 'login'), namespace='login')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

login/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path(r'login/', login_view, name='login'),
    path(r'logout/', logout_view, name='logout'),
]

Program/models.py
from django.db import models

# Create your models here.
class Program(models.Model):
    kodeProgram = models.CharField(max_length=50)
    judul = models.CharField(max_length=50)
    nama = models.CharField(max_length=100)
    tanggal = models.CharField(max_length=100)
    link = models.CharField(max_length=100)
    deskripsi = models.CharField(max_length=500)
    kodeDonasi = models.CharField(max_length=500)

Program/views.py
from django.shortcuts import render, redirect
from django.urls import resolve
from Donation.models import donasi
from .models import Program

response = {}
def program(request):
    response['kode'] = 'default'
    url = resolve(request.path).url_name
    for program in Program.objects.all():
        if (program.kodeProgram == url):
            response["judul"] = program.judul
            response["nama"] = program.nama
            response["tanggal"] = program.tanggal
            response["deskripsi"] = program.deskripsi
            response["link"] = program.link
            response['kode'] = program.kodeDonasi
            response["donasi"] = calculateAll(response["kode"])
            break
    if (response["kode"] == "default"):
        return redirect('donasi')
    return render(request, 'baseProgram.html', response)

def calculateAll(type):
    uang = 0
    for donation in donasi.objects.all():
        if (donation.program == type):
            uang += donation.jumlah_donasi
    if (uang>0):
        return "Donasi yang Telah Terkumpul Sebesar Rp. {}".format(uang)
    return "Belum ada donasi. Jadilah yang pertama!"

Program/templates/baseProgram.html
{% extends 'Base/Base.html' %}
{% load static %}
{% block content %}
<head>
    {% block title %}
        <title>SinarPerak - Program</title>
    {% endblock %}
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-11" style="margin : auto">
                <h1>{% block judul %}{{ judul }}{% endblock %}</h1>
                <br>
            </div>
        </div>
    </div>
    <div class="container-fluid" style="padding : 0px">
        <img src="{% block source %}{{ link }}{% endblock %}" class="img-responsive" style="border-radius : 15px">
        <br>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-11" style="margin : auto">
                <h3>{% block subjudul %}{{ nama }} Pada Tanggal {{ tanggal }}{% endblock %}</h3>
                <h4>{% block duit %}{{ donasi }}{% endblock %}</h4>
                <h5>Kode Program: {{ kode }}</h5>
                <br><br>
                {% if user.is_authenticated %}
                    <a href={% url 'Submission' %} class="btn btn-primary btn-lg role="button" style="background-color : black">Saya ingin donasi</a>
                {% else %}
                    <a onclick="login()" href={% url 'login:login' %} class="btn btn-primary btn-lg role="button" style="background-color : black">Donasi</a>
                    <script>
                        function login(){
                            alert("Please log in with your Google account!");
                        }
                    </script>
                {% endif %}
                <br>
                <hr style="border-width : 5px; border-color : black">
                <br><br>
                <p style="font-size : 17px" align="justify">{% block paragraph %}{{ deskripsi }}{% endblock %}</p>
                <br><br><br>
            </div>
        </div>
    </div>
</body>
{% endblock %}